name: JscramblerTest
on:
  workflow_call:
    inputs:
        MODULE_NAME:
          description: "Module to scan"
          required: true
          type: string
        LANGUAGE:
          description: "Language to scan"
          required: true
          type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install jscrambler
        run: |
             pwd
             npm install -g jscrambler
             npm run build
             npm run start
        


