name: JscramblerTest
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install jscrambler
        run: |
             pwd
             npm install -g jscrambler
        


