name: JscramblerTest
on:
  workflow_call:
    secrets:
        data:
          required: true
        data1:
          required: true  


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install jscrambler
        run: |
             pwd
             npm i
             npm install -g jscrambler
             npm run build
      - uses: ./
        with: 
          host: ${{ secrets.data }}
          login: ${{ secrets.data1 }}
          
           
        


