name: testing reusable workflows

on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v2
      - name: testing 
        run: echo "this is reusable workflow test!"
